name: FlagsDamage
version: 1.0.0
description: Module that adds damage flags to the Flags plugin.
author: Alshain01
website: http://dev.bukkit.org/bukkit-plugins/flags/
main: alshain01.FlagsDamage.FlagsDamage
depend: [Flags]